image: python:3.7-alpine

stages:
  - test
  
before_script:
- apk update
- apk add doxygen
- apk add libxml2-dev
- apk add libxslt1-dev
## Uncomment the following line if you use graphviz dot graphs
#- apk add ttf-freefont graphviz

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - python -m venv venv
  - source venv/bin/activate
  - pip install --upgrade pip
  - pip install lxml
  - pip install doxygen-interface


test:
  script:
  #- doxygen .ci_cd/fdl_html_translator_xslt/Doxyfile
    - cd .ci_cd/fdl_html_translator_xslt/
    - python generate_html_documentation.py
    - pwd
    - ls docs
    - cd ../..
    - pwd
  except:
    - master
  
pages:
  script:
    #- doxygen .ci_cd/fdl_html_translator_xslt/Doxyfile
    - cd .ci_cd/fdl_html_translator_xslt/
    - python generate_html_documentation.py
    - mv docs/html/ ../../public/
    - cd ../..
  artifacts:
    paths:
     - public
  only:
    - master

feature_test:
    #image: moeryomenko/python-docker-lxml
    stage: test
    script: 
      - pwd
      #- python validate_features.py

