image: python:3.7-slim-buster

stages:
  - test



variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - apt-get update
  - apt-get install --yes doxygen
  ## Uncomment the following line if you use graphviz dot graphs
  #- apt-get install ttf-freefont graphviz

  - python -V  # Print out python version for debugging
  - python -m venv venv
  - source venv/bin/activate
  - pip install --upgrade pip
  - pip install lxml
  - pip install doxygen-interface

test:
  script:
    - cd tools/fdl_html_translator_xslt/
    - python generate_html_documentation.py

  #except:
  #  - master

pages:
  script:
    - cd tools/fdl_html_translator_xslt/
    - python generate_html_documentation.py
    - mv docs/html/ ../../public/

  artifacts:
    paths:
     - public
  #only:
  #  - master

feature_test:
    #image: moeryomenko/python-docker-lxml
    stage: test
    script:
      - python .ci_cd/validate_features.py
