# Uses NodeJS V 9.4.0
image: node:latest

stages:
  - manual
  - build
  - test_node
  - test_python
  - deploy

feature_test:
    image: lgatica/python-alpine:3.6.3
    stage: test_python
    before_script:
      - pip install lxml
      - cd tools/feature_validator
    script:
      - python validate_features.py


# Manual Job to setup manual execution of the CI
start:
  stage: manual
  when: manual
  allow_failure: false
  script: echo "Starting to validate and verify"
  except:
    - master

build:
  stage: build
  before_script:
    - cd tools/documentation_app
    - npm install
  script:
    - npm run build
    - npm test
  artifacts:
    paths:
      - tools/documentation_app/node_modules
      - tools/documentation_app/build

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r tools/documentation_app/build/* .public
    - mv .public public
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
  dependencies:
    - build
  only:
    - master
